import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, extname, isAbsolute, join } from "node:path";
import type { ExtensionAPI, ExtensionContext, SessionEntry } from "@earendil-works/pi-coding-agent";
import { Text, truncateToWidth } from "@earendil-works/pi-tui";
import { Type } from "typebox";
import { discoverAgents, type AgentDefinition, type AgentScope } from "./agents.js";
import { appendRunHistory } from "./history.js";
import { validateExecutionPolicy } from "./policy.js";
import { normalizeDagYaml, normalizeNestedWorkflows } from "./dag-yaml.js";
import { PiSdkRunner } from "./runner.js";
import type { ChainStep, ExecutionOptions, FlowMode, FlowResult, SubagentResult, SubagentRunner, SubagentTask } from "./types.js";
import { runChain } from "./flows/chain.js";
import { runDag } from "./flows/dag.js";
import { runParallel } from "./flows/parallel.js";
import { runSingle } from "./flows/single.js";

export interface PiSubflowExtensionOptions {
	userDir?: string;
	projectDir?: string;
	userSubflowDir?: string;
	historyPath?: string | ((ctx: ExtensionContext) => string);
	allowedTools?: string[];
	runnerFactory?: (input: { agents: Map<string, AgentDefinition>; ctx: ExtensionContext; params: SubflowToolParams }) => SubagentRunner;
}

type RiskTolerance = "low" | "medium" | "high";
type WorkflowTasksValue = NonNullable<NonNullable<SubagentTask["workflow"]>["tasks"]>;

const DEFAULT_ALLOWED_TOOLS = new Set(["read", "bash", "grep", "find", "ls", "edit", "write"]);
const GENERATED_PROMPT_STUB_MARKER = "<!-- generated by pi-subflow workflow prompt stubs; do not edit -->";
const MAX_WORKFLOW_CONTEXT_CHARS = 12000;

interface SubflowToolParams {
	agent?: string;
	task?: string;
	role?: SubagentTask["role"];
	tools?: string[];
	model?: string;
	thinking?: SubagentTask["thinking"];
	tasks?: SubagentTask[];
	dagYaml?: string;
	chain?: ChainStep[];
	agentScope?: AgentScope;
	confirmProjectAgents?: boolean;
	riskTolerance?: RiskTolerance;
	allowExternalSideEffectWithoutConfirmation?: boolean;
	maxConcurrency?: number;
	timeoutSeconds?: number;
	maxRetries?: number;
	maxCost?: number;
	maxTokens?: number;
	maxTurns?: number;
	maxVerificationRounds?: number;
}

const workflowSchema = Type.Object({
	tasks: Type.Optional(Type.Any()),
	dagYaml: Type.Optional(Type.String()),
	uses: Type.Optional(Type.String()),
});

const taskSchema = Type.Object({
	name: Type.Optional(Type.String({ minLength: 1 })),
	agent: Type.Optional(Type.String({ minLength: 1 })),
	task: Type.Optional(Type.String({ minLength: 1 })),
	workflow: Type.Optional(workflowSchema),
	loop: Type.Optional(Type.Object({
		maxIterations: Type.Number(),
		body: Type.Any(),
		until: Type.Optional(Type.String({ minLength: 1 })),
	})),
	cwd: Type.Optional(Type.String()),
	dependsOn: Type.Optional(Type.Array(Type.String())),
	when: Type.Optional(Type.String()),
	role: Type.Optional(Type.Union([Type.Literal("worker"), Type.Literal("verifier")])),
	authority: Type.Optional(Type.Union([Type.Literal("read_only"), Type.Literal("internal_mutation"), Type.Literal("external_side_effect")])),
	tools: Type.Optional(Type.Array(Type.String({ minLength: 1 }))),
	model: Type.Optional(Type.String()),
	thinking: Type.Optional(Type.Union([Type.Literal("off"), Type.Literal("minimal"), Type.Literal("low"), Type.Literal("medium"), Type.Literal("high"), Type.Literal("xhigh")])),
	expectedSections: Type.Optional(Type.Array(Type.String())),
	jsonSchema: Type.Optional(Type.Object({ required: Type.Optional(Type.Array(Type.String())) })),
});

const chainStepSchema = Type.Object({
	agent: Type.String({ minLength: 1 }),
	task: Type.String({ minLength: 1 }),
	cwd: Type.Optional(Type.String()),
	tools: Type.Optional(Type.Array(Type.String({ minLength: 1 }))),
	model: Type.Optional(Type.String()),
	thinking: Type.Optional(Type.Union([Type.Literal("off"), Type.Literal("minimal"), Type.Literal("low"), Type.Literal("medium"), Type.Literal("high"), Type.Literal("xhigh")])),
});

export function registerPiSubflowExtension(pi: Pick<ExtensionAPI, "registerTool" | "registerCommand" | "on" | "sendMessage">, options: PiSubflowExtensionOptions = {}): void {
	pi.registerTool({
		name: "subflow",
		label: "Pi Subflow",
		description: "Delegate bounded work to isolated Pi subagents using the pi-subflow orchestration core.",
		promptSnippet: "subflow: delegate bounded work to isolated Pi subagents; supports single, chain, parallel, DAG, conditional edges, bounded loops, and nested workflow task execution.",
		promptGuidelines: [
			"Use subflow only for bounded multi-agent work with clear inputs/outputs; skip it for small direct tasks.",
			"Modes: single=one focused task; chain=later steps consume {previous}; parallel=2+ independent tasks; DAG=explicit dependsOn, conditional when edges, verifier fan-in, or bounded loops; loop=repeat a namespaced body with loop.maxIterations and optional until.",
			"Use subflow DAG mode with role: \"verifier\" for synthesis/validation needing dependency outputs; task names must be unique, and missing deps/self-deps/cycles fail before execution.",
			"For LLM-authored DAGs prefer dagYaml: YAML mapping task names to fields; needs aliases dependsOn, but do not set both.",
			"Nested workflows use workflow.tasks or workflow.dagYaml; workflow.uses is reserved/schema-only for now; children are namespaced under the parent task, parent dependsOn flows into workflow roots, and downstream tasks can depend on the parent workflow name to read its synthetic summary.",
			"Bounded loops use loop.maxIterations (capped at 100) with a body mapping or array; iteration bodies are namespaced per pass, inherit parent dependencies on the first pass, and can stop early when until resolves true against current-iteration aliases like ${editor.output.continue}.",
			"Use when for conditional DAG execution with placeholders like ${task.output.path}; references must point to existing dependency tasks, false conditions skip the task, and invalid expressions fail.",
			"Workflow commands: safe .pi/subflow/workflows/*.{yaml,yml} and ~/.pi/agent/subflow/workflows/*.{yaml,yml} register at session start as /stem; generated stubs go in matching prompts dirs only if no manual file exists or replacing marked stubs; UI/autocomplete depends on prompt discovery/session registration.",
			"Workflow commands prepend recent chat history plus command text to every task, use \"(none provided)\" for empty args, and finish with a notification plus chat-history result.",
			"For roles, only use \"worker\" or \"verifier\"; omit role for worker and do not invent roles like \"researcher\".",
			"Set the minimum tool subset each subagent needs; omit tools only for the default Pi set. Set model/thinking per task when quality/cost differ; thinking: off,minimal,low,medium,high,xhigh.",
			"Safety/output: external_side_effect is high-risk and needs UI confirmation unless explicitly allowed with sufficient risk tolerance; use expectedSections for markdown and jsonSchema.required only for minimal JSON required-field checks, not full JSON Schema.",
		],
		renderShell: "self",
		parameters: Type.Object({
			agent: Type.Optional(Type.String({ minLength: 1, description: "Agent name for single-task mode." })),
			task: Type.Optional(Type.String({ minLength: 1, description: "Task text for single-task mode." })),
			tasks: Type.Optional(Type.Array(taskSchema, { description: "Parallel or DAG tasks. dependsOn enables DAG mode." })),
			dagYaml: Type.Optional(Type.String({ description: "YAML shorthand for DAG tasks. Root is a mapping of task names to task fields; needs is an alias for dependsOn." })),
			chain: Type.Optional(Type.Array(chainStepSchema, { description: "Sequential chain steps; later steps may use {previous}." })),
			agentScope: Type.Optional(Type.Union([Type.Literal("user"), Type.Literal("project"), Type.Literal("both")], { default: "user" })),
			confirmProjectAgents: Type.Optional(Type.Boolean({ default: true })),
			riskTolerance: Type.Optional(Type.Union([Type.Literal("low"), Type.Literal("medium"), Type.Literal("high")], { default: "low" })),
			allowExternalSideEffectWithoutConfirmation: Type.Optional(Type.Boolean({ default: false })),
			maxConcurrency: Type.Optional(Type.Number()),
			timeoutSeconds: Type.Optional(Type.Number()),
			maxRetries: Type.Optional(Type.Number()),
			maxCost: Type.Optional(Type.Number()),
			maxTokens: Type.Optional(Type.Number()),
			maxTurns: Type.Optional(Type.Number()),
			maxVerificationRounds: Type.Optional(Type.Number()),
			model: Type.Optional(Type.String()),
			thinking: Type.Optional(Type.Union([Type.Literal("off"), Type.Literal("minimal"), Type.Literal("low"), Type.Literal("medium"), Type.Literal("high"), Type.Literal("xhigh")])),
			role: Type.Optional(Type.Union([Type.Literal("worker"), Type.Literal("verifier")])),
			tools: Type.Optional(Type.Array(Type.String({ minLength: 1 }))),
		}),
		renderCall(args) {
			return new Text(formatCall(args as SubflowToolParams), 0, 0);
		},
		renderResult(result) {
			const details = result.details as (FlowResult & { mode?: FlowMode }) | undefined;
			const text = details?.mode ? formatResult(details, details.mode) : result.content.map((item) => item.type === "text" ? item.text : "").join("\n");
			return new Text(text, 0, 0);
		},
		async execute(_toolCallId, rawParams, signal, _onUpdate, ctx) {
			return executeSubflow(rawParams as SubflowToolParams, ctx, options, signal);
		},
	});

	const registeredWorkflowCommands = new Map<string, string>();
	pi.on("resources_discover", async (event) => {
		const userSubflowDir = resolveUserSubflowDir(options);
		const workflows = await discoverWorkflowCommands(event.cwd, userSubflowDir);
		const promptPaths = await writeWorkflowPromptStubs(workflows, workflowPromptDirs(event.cwd, userSubflowDir));
		return promptPaths.length > 0 ? { promptPaths } : {};
	});
	pi.on("session_start", async (_event, ctx) => {
		const workflows = chooseWorkflowCommands(await discoverWorkflowCommands(ctx.cwd, resolveUserSubflowDir(options)));
		for (const workflow of workflows) {
			const { commandName } = workflow;
			if (registeredWorkflowCommands.get(commandName) === workflow.path) continue;
			registeredWorkflowCommands.set(commandName, workflow.path);
			pi.registerCommand(commandName, {
				description: `Run ${workflow.displayPath} as a pi-subflow DAG`,
				handler: async (args, commandCtx) => {
					const dagYaml = await readFile(workflow.path, "utf8");
					const workflowParams = normalizeDagYaml({ dagYaml, agentScope: "both" as const });
					const { dagYaml: _dagYaml, ...normalizedParams } = workflowParams;
					const executableParams = addWorkflowCommandArguments(normalizedParams, args, formatRecentConversationContext(commandCtx));
					validateWorkflowCommandCwds(executableParams.tasks ?? []);
					const result = await executeSubflow(executableParams, commandCtx, options, commandCtx.signal);
					commandCtx.ui.notify(`Workflow /${commandName} ${result.isError ? "failed" : "completed"}`, result.isError ? "error" : "info");
					pi.sendMessage({
						customType: "pi-subflow.workflow-result",
						content: formatWorkflowChatResult(commandName, result),
						display: true,
						details: { commandName, status: result.isError ? "failed" : "completed" },
					}, { triggerTurn: false, deliverAs: "followUp" });
				},
			});
		}
	});
}

export default function piSubflowExtension(pi: ExtensionAPI): void {
	registerPiSubflowExtension(pi);
}

async function executeSubflow(rawParams: SubflowToolParams, ctx: ExtensionContext, options: PiSubflowExtensionOptions, signal?: AbortSignal) {
	const params = normalizeNestedWorkflows(normalizeDagYaml(rawParams));
	const mode = inferMode(params);
	const flowTasks = tasksForPolicy(params);
	validateNonEmptyStrings(flowTasks);
	validateExecutionPolicy({
		agentScope: params.agentScope,
		confirmProjectAgents: params.confirmProjectAgents,
		hasUI: ctx.hasUI,
		riskTolerance: params.riskTolerance,
		allowExternalSideEffectWithoutConfirmation: params.allowExternalSideEffectWithoutConfirmation,
		tasks: flowTasks,
	});
	await confirmPolicies(params, flowTasks, ctx);
	const agents = await discoverAgents({
		scope: params.agentScope ?? "user",
		userDir: options.userDir ?? join(homedir(), ".pi", "agent", "agents"),
		projectDir: options.projectDir ?? join(ctx.cwd, ".pi", "agents"),
	});
	const effectiveParams = applyAgentDefaults(params, agents, ctx.cwd);
	const effectiveTasks = tasksForPolicy(effectiveParams);
	validateToolAllowlist(effectiveTasks, options.allowedTools);
	const baseRunner = options.runnerFactory?.({ agents, ctx, params: effectiveParams }) ?? new PiSdkRunner({ agentDefinitions: agents });
	const progress = createProgressReporter(ctx, mode, effectiveTasks.length, params.timeoutSeconds);
	const runner = progress ? new ProgressRunner(baseRunner, progress) : baseRunner;
	progress?.start();
	const executionOptions: ExecutionOptions = {
		runner,
		maxConcurrency: params.maxConcurrency,
		timeoutSeconds: params.timeoutSeconds,
		maxRetries: params.maxRetries,
		maxCost: params.maxCost,
		maxTokens: params.maxTokens,
		maxTurns: params.maxTurns,
		maxVerificationRounds: params.maxVerificationRounds,
		signal: signal ?? ctx.signal,
	};
	let result: FlowResult;
	try {
		result = await runSelectedFlow(mode, effectiveParams, executionOptions);
	} finally {
		progress?.clear();
	}
	await appendRunHistory(resolveHistoryPath(options.historyPath, ctx), { ...result, mode });
	const details = { ...result, mode };
	return {
		content: [{ type: "text" as const, text: formatResult(result, mode) }],
		details,
		isError: result.status !== "completed",
	};
}

interface WorkflowCommandFile {
	commandName: string;
	entry: string;
	path: string;
	promptDir: string;
	displayPath: string;
	scope: "project" | "user";
}

function resolveUserSubflowDir(options: PiSubflowExtensionOptions): string {
	return options.userSubflowDir ?? join(homedir(), ".pi", "agent", "subflow");
}

function workflowPromptDirs(cwd: string, userSubflowDir: string): string[] {
	return [join(cwd, ".pi", "subflow", "prompts"), join(userSubflowDir, "prompts")];
}

async function discoverWorkflowCommands(cwd: string, userSubflowDir: string): Promise<WorkflowCommandFile[]> {
	const projectWorkflows = await discoverWorkflowCommandsInDir({
		workflowDir: join(cwd, ".pi", "subflow", "workflows"),
		promptDir: join(cwd, ".pi", "subflow", "prompts"),
		displayPrefix: ".pi/subflow/workflows",
		scope: "project",
	});
	const userWorkflows = await discoverWorkflowCommandsInDir({
		workflowDir: join(userSubflowDir, "workflows"),
		promptDir: join(userSubflowDir, "prompts"),
		displayPrefix: "~/.pi/agent/subflow/workflows",
		scope: "user",
	});
	return [...projectWorkflows, ...userWorkflows];
}

function chooseWorkflowCommands(workflows: WorkflowCommandFile[]): WorkflowCommandFile[] {
	const byCommand = new Map<string, WorkflowCommandFile>();
	for (const workflow of workflows) if (!byCommand.has(workflow.commandName)) byCommand.set(workflow.commandName, workflow);
	return Array.from(byCommand.values());
}

async function discoverWorkflowCommandsInDir({ workflowDir, promptDir, displayPrefix, scope }: { workflowDir: string; promptDir: string; displayPrefix: string; scope: WorkflowCommandFile["scope"] }): Promise<WorkflowCommandFile[]> {
	let entries: string[];
	try {
		entries = await readdir(workflowDir);
	} catch (error) {
		if (isNodeError(error) && error.code === "ENOENT") return [];
		throw error;
	}
	return entries.sort().flatMap((entry) => {
		const extension = extname(entry);
		if (extension !== ".yaml" && extension !== ".yml") return [];
		const commandName = basename(entry, extension);
		return isSafeWorkflowCommandName(commandName) ? [{ commandName, entry, path: join(workflowDir, entry), promptDir, displayPath: `${displayPrefix}/${entry}`, scope }] : [];
	});
}

async function writeWorkflowPromptStubs(workflows: WorkflowCommandFile[], knownPromptDirs: string[]): Promise<string[]> {
	const workflowsByPromptDir = new Map<string, WorkflowCommandFile[]>();
	for (const promptDir of knownPromptDirs) workflowsByPromptDir.set(promptDir, []);
	for (const workflow of workflows) workflowsByPromptDir.set(workflow.promptDir, [...(workflowsByPromptDir.get(workflow.promptDir) ?? []), workflow]);
	const promptPaths: string[] = [];
	for (const [promptDir, promptDirWorkflows] of workflowsByPromptDir) {
		const activeFiles = new Set(promptDirWorkflows.map(({ commandName }) => `${commandName}.md`));
		let entries: string[] = [];
		try {
			entries = await readdir(promptDir);
		} catch (error) {
			if (!isNodeError(error) || error.code !== "ENOENT") throw error;
		}
		for (const entry of entries) {
			if (entry.endsWith(".md") && !activeFiles.has(entry) && await isGeneratedWorkflowPromptStub(join(promptDir, entry))) await rm(join(promptDir, entry), { force: true });
		}
		if (promptDirWorkflows.length === 0) continue;
		await mkdir(promptDir, { recursive: true });
		for (const workflow of promptDirWorkflows) {
			const promptPath = join(promptDir, `${workflow.commandName}.md`);
			if (await shouldWriteWorkflowPromptStub(promptPath)) await writeFile(promptPath, workflowPromptStubContent(workflow), "utf8");
		}
		promptPaths.push(promptDir);
	}
	return promptPaths;
}

async function shouldWriteWorkflowPromptStub(path: string): Promise<boolean> {
	try {
		return (await readFile(path, "utf8")).includes(GENERATED_PROMPT_STUB_MARKER);
	} catch (error) {
		if (isNodeError(error) && error.code === "ENOENT") return true;
		throw error;
	}
}

async function isGeneratedWorkflowPromptStub(path: string): Promise<boolean> {
	try {
		return (await readFile(path, "utf8")).includes(GENERATED_PROMPT_STUB_MARKER);
	} catch (error) {
		if (isNodeError(error) && error.code === "ENOENT") return false;
		throw error;
	}
}

function workflowPromptStubContent({ commandName, displayPath }: WorkflowCommandFile): string {
	return [GENERATED_PROMPT_STUB_MARKER, `---`, `description: Run ${displayPath} as a pi-subflow DAG`, `argument-hint: [workflow arguments]`, `---`, `/${commandName} $ARGUMENTS`, ""].join("\n");
}

function formatWorkflowChatResult(commandName: string, result: Awaited<ReturnType<typeof executeSubflow>>): string {
	const status = result.isError ? "failed" : "completed";
	const summary = result.content.map((item) => item.type === "text" ? item.text : "").filter(Boolean).join("\n").trim();
	const finalOutput = result.details.output.trim();
	const lines = [`Workflow /${commandName} ${status}`];
	if (summary) lines.push("", "Summary:", summary);
	if (finalOutput) lines.push("", "Final output:", finalOutput);
	return lines.join("\n");
}

function isSafeWorkflowCommandName(name: string): boolean {
	return /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(name);
}

function validateWorkflowCommandCwds(tasks: SubagentTask[]): void {
	for (const task of tasks) {
		if (!task.cwd) continue;
		if (isAbsolute(task.cwd) || task.cwd.split(/[\\/]+/).includes("..")) {
			throw new Error(`workflow command task ${task.name ?? task.agent} cwd must stay inside the project`);
		}
	}
}

function addWorkflowCommandArguments(params: SubflowToolParams, args: string, recentContext?: string): SubflowToolParams {
	const workflowArgs = args.trim() || "(none provided)";
	const contextPrefix = recentContext ? ["Recent conversation context:", recentContext, ""] : [];
	return {
		...params,
		tasks: params.tasks?.map((task) => task.task == null ? task : {
			...task,
			task: [...contextPrefix, `Workflow command arguments:`, workflowArgs, "", "Workflow task:", task.task].join("\n"),
		}),
	};
}

function formatRecentConversationContext(ctx: ExtensionContext): string | undefined {
	const entries = ctx.sessionManager?.getBranch?.() ?? [];
	const text = entries.map(formatSessionEntryForWorkflowContext).filter(Boolean).join("\n\n").trim();
	if (!text) return undefined;
	return text.length > MAX_WORKFLOW_CONTEXT_CHARS ? `[truncated to recent context]\n${text.slice(-MAX_WORKFLOW_CONTEXT_CHARS)}` : text;
}

function formatSessionEntryForWorkflowContext(entry: SessionEntry): string {
	if (entry.type === "message") return formatAgentMessageForWorkflowContext(entry.message);
	if (entry.type === "custom_message") return [`[${entry.customType}]`, contentToText(entry.content)].filter(Boolean).join("\n");
	if (entry.type === "compaction") return [`[compaction summary]`, entry.summary].filter(Boolean).join("\n");
	if (entry.type === "branch_summary") return [`[branch summary]`, entry.summary].filter(Boolean).join("\n");
	return "";
}

function formatAgentMessageForWorkflowContext(message: any): string {
	if (message.role === "user") return [`User:`, contentToText(message.content)].filter(Boolean).join("\n");
	if (message.role === "assistant") return [`Assistant:`, contentToText(message.content)].filter(Boolean).join("\n");
	if (message.role === "toolResult") return [`Tool result (${message.toolName}):`, contentToText(message.content)].filter(Boolean).join("\n");
	if (message.role === "custom") return [`[${message.customType}]`, contentToText(message.content)].filter(Boolean).join("\n");
	return "";
}

function contentToText(content: unknown): string {
	if (typeof content === "string") return content.trim();
	if (!Array.isArray(content)) return "";
	return content.map((item) => {
		if (typeof item === "string") return item;
		if (!isRecord(item)) return "";
		return typeof item.text === "string" ? item.text : "";
	}).filter(Boolean).join("\n").trim();
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
	return error instanceof Error && "code" in error;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

async function confirmPolicies(params: SubflowToolParams, tasks: SubagentTask[], ctx: ExtensionContext): Promise<void> {
	const scope = params.agentScope ?? "user";
	if ((scope === "project" || scope === "both") && params.confirmProjectAgents !== false && ctx.hasUI) {
		const ok = await ctx.ui.confirm("Use project-local agents?", "Project-local agent definitions can override user agents. Continue?");
		if (!ok) throw new Error("project-local agent use declined");
	}
	const needsExternalConfirmation = tasks.some((task) => task.authority === "external_side_effect") && !params.allowExternalSideEffectWithoutConfirmation && ctx.hasUI;
	if (needsExternalConfirmation) {
		const ok = await ctx.ui.confirm("Allow external side effects?", "One or more subagent tasks requested authority: external_side_effect. Continue?");
		if (!ok) throw new Error("external_side_effect authority declined");
	}
}

function inferMode(params: SubflowToolParams): FlowMode {
	if (params.chain) return "chain";
	if (params.dagYaml) return "dag";
	if (params.tasks) return containsNestedWorkflowOrLoop(params.tasks) || params.tasks.some((task) => task.dependsOn?.length || task.role === "verifier") ? "dag" : "parallel";
	if (params.agent && params.task) return "single";
	throw new Error("subflow requires either agent+task, chain, dagYaml, or tasks");
}

function validateNonEmptyStrings(tasks: SubagentTask[]): void {
	for (const task of tasks) {
		if (task.workflow || task.loop) continue;
		if (!task.agent?.trim()) throw new Error("agent must be a non-empty string");
		if (!task.task?.trim()) throw new Error("task must be a non-empty string");
	}
}

function tasksForPolicy(params: SubflowToolParams): SubagentTask[] {
	if (params.tasks) return flattenPolicyTasks(params.tasks);
	if (params.dagYaml) return flattenPolicyTasks(normalizeDagYaml(params).tasks ?? []);
	if (params.chain) return params.chain.map((step) => ({ ...step }));
	if (params.agent && params.task) return [{ ...(params as SubagentTask), agent: params.agent, task: params.task }];
	return [];
}

function flattenPolicyTasks(tasks: SubagentTask[]): SubagentTask[] {
	const flattened: SubagentTask[] = [];
	for (const task of tasks) {
		if (task.workflow?.tasks) flattened.push(...flattenPolicyWorkflowTasks(task.workflow.tasks));
		else if (task.loop?.body) flattened.push(...flattenPolicyLoopTasks(task.loop.body));
		else flattened.push(task);
	}
	return flattened;
}

function flattenPolicyWorkflowTasks(tasks: WorkflowTasksValue): SubagentTask[] {
	if (Array.isArray(tasks)) return tasks.flatMap((task) => task.workflow?.tasks ? flattenPolicyWorkflowTasks(task.workflow.tasks) : task.loop?.body ? flattenPolicyLoopTasks(task.loop.body) : [task]);
	if (isRecord(tasks)) return Object.values(tasks).flatMap((task) => task.workflow?.tasks ? flattenPolicyWorkflowTasks(task.workflow.tasks) : task.loop?.body ? flattenPolicyLoopTasks(task.loop.body) : [task]);
	return [];
}

function flattenPolicyLoopTasks(tasks: NonNullable<SubagentTask["loop"]>["body"]): SubagentTask[] {
	if (Array.isArray(tasks)) return tasks.flatMap((task) => task.workflow?.tasks ? flattenPolicyWorkflowTasks(task.workflow.tasks) : task.loop?.body ? flattenPolicyLoopTasks(task.loop.body) : [task]);
	if (isRecord(tasks)) return Object.values(tasks).flatMap((task) => task.workflow?.tasks ? flattenPolicyWorkflowTasks(task.workflow.tasks) : task.loop?.body ? flattenPolicyLoopTasks(task.loop.body) : [task]);
	return [];
}

function validateToolAllowlist(tasks: SubagentTask[], allowedTools?: string[]): void {
	const allowlist = allowedTools ? new Set(allowedTools) : DEFAULT_ALLOWED_TOOLS;
	for (const task of tasks) {
		for (const tool of task.tools ?? []) {
			if (!allowlist.has(tool)) throw new Error(`unknown or unavailable tool: ${tool}`);
		}
	}
}

function applyAgentDefaults(params: SubflowToolParams, agents: Map<string, AgentDefinition>, defaultCwd: string): SubflowToolParams {
	const apply = <T extends SubagentTask | ChainStep>(task: T): T => {
		const agent = task.agent ? agents.get(task.agent) : undefined;
		const workflow = isWorkflowTask(task) && task.workflow ? {
			...task.workflow,
			tasks: Array.isArray(task.workflow.tasks)
				? task.workflow.tasks.map((child) => apply(child as SubagentTask))
				: isRecord(task.workflow.tasks)
					? Object.fromEntries(Object.entries(task.workflow.tasks).map(([name, child]) => [name, apply(child as SubagentTask)]))
					: task.workflow.tasks,
		} : undefined;
		const loop = "loop" in task && task.loop ? {
			...task.loop,
			body: Array.isArray(task.loop.body)
				? task.loop.body.map((child) => apply(child as SubagentTask))
				: isRecord(task.loop.body)
					? Object.fromEntries(Object.entries(task.loop.body).map(([name, child]) => [name, apply(child as SubagentTask)]))
					: task.loop.body,
		} : undefined;
		return {
			...task,
			workflow,
			loop,
			cwd: task.cwd ?? defaultCwd,
			tools: task.tools ?? agent?.tools,
			model: task.model ?? agent?.model,
			thinking: task.thinking ?? (agent?.thinking as SubagentTask["thinking"] | undefined),
		};
	};
	return {
		...params,
		tasks: params.tasks?.map(apply),
		chain: params.chain?.map(apply),
		...(params.agent && params.task ? apply({ ...(params as SubagentTask), agent: params.agent, task: params.task }) : {}),
	};
}

function containsNestedWorkflowOrLoop(tasks: SubagentTask[]): boolean {
	return tasks.some((task) => Boolean(task.workflow || task.loop));
}

function isWorkflowTask(task: SubagentTask | ChainStep): task is SubagentTask {
	return "workflow" in task;
}

function normalizeLoopBody(tasks: NonNullable<SubagentTask["loop"]>["body"], context: string): NonNullable<SubagentTask["loop"]>["body"] {
	if (Array.isArray(tasks)) return tasks.map((task, index) => normalizeNestedWorkflows({ tasks: [{ ...task, name: task.name ?? `${task.agent ?? "task"}-${index + 1}` }] }).tasks?.[0]!);
	if (isRecord(tasks)) return Object.fromEntries(Object.entries(tasks).map(([name, task]) => [name, normalizeNestedWorkflows({ tasks: [{ ...task, name: task.name ?? name }] }).tasks?.[0]!]));
	throw new Error(`${context} loop body must be an array or mapping`);
}

class ProgressRunner implements SubagentRunner {
	constructor(private readonly inner: SubagentRunner, private readonly progress: ProgressReporter) {}

	async run(input: import("./types.js").RunnerInput, signal?: AbortSignal): Promise<SubagentResult> {
		this.progress.taskStarted(input);
		try {
			const result = await this.inner.run(input, signal);
			this.progress.taskFinished(result);
			return result;
		} catch (error) {
			this.progress.taskFinished({ name: input.name, agent: input.agent ?? "workflow", task: input.task ?? "summary", role: input.role, model: input.model, status: "failed", output: "", error: error instanceof Error ? error.message : String(error), usage: {} });
			throw error;
		}
	}
}

interface ProgressReporter {
	start(): void;
	taskStarted(task: import("./types.js").RunnerInput): void;
	taskFinished(result: SubagentResult): void;
	clear(): void;
}

function createProgressReporter(ctx: ExtensionContext, mode: string, total: number, timeoutSeconds?: number): ProgressReporter | undefined {
	if (!ctx.hasUI) return undefined;
	const ui = ctx.ui as unknown;
	if (typeof ui !== "object" || ui === null || !("setWidget" in ui) || typeof ui.setWidget !== "function") return undefined;
	const setWidget = ui.setWidget;
	const startedAt = Date.now();
	const running = new Map<string, { startedAt: number; task: import("./types.js").RunnerInput }>();
	const results = new Map<string, SubagentResult>();
	let interval: ReturnType<typeof setInterval> | undefined;
	let runningFrame = 0;
	let stopped = false;
	const stop = () => {
		if (interval) clearInterval(interval);
		interval = undefined;
		stopped = true;
	};
	const safeSetWidget = (value: unknown, options?: unknown): boolean => {
		if (stopped) return false;
		try {
			setWidget.call(ui, "pi-subflow-progress", value, options);
			return true;
		} catch {
			stop();
			return false;
		}
	};
	const render = () => {
		if (stopped) return;
		const completed = [...results.values()].filter((result) => result.status === "completed").length;
		const failed = [...results.values()].filter((result) => result.status === "failed").length;
		const skipped = [...results.values()].filter((result) => result.status === "skipped").length;
		const runningCount = [...running.keys()].filter((name) => !results.has(name)).length;
		const status = failed > 0 ? "failed" : completed + skipped >= total && total > 0 ? "completed" : "running";
		const timeout = timeoutSeconds ? ` · ${timeoutSeconds}s timeout` : "";
		const elapsed = formatDuration(Date.now() - startedAt);
		const runningIcon = statusIcon("running", runningFrame);
		const taskLines = [
			...[...results.values()].map((result) => `${statusIcon(result.status, runningFrame)} ${result.name ?? result.agent} ${formatTaskIdentity(result)}${result.error ? `: ${result.error}` : result.output ? ` → ${firstLine(result.output)}` : ""}`),
			...[...running.entries()].filter(([name]) => !results.has(name)).map(([name, state]) => `${runningIcon} ${name} ${formatTaskIdentity(state.task)} · ${formatDuration(Date.now() - state.startedAt)} elapsed`),
		];
		const lines = [
			`subflow · ${mode} · ${status}`,
			`${total} task${total === 1 ? "" : "s"} · ${runningCount} running · ${completed} completed · ${failed} failed · ${skipped} skipped · ${elapsed} elapsed${timeout}`,
			...(taskLines.length ? taskLines : ["waiting to start"]),
		];
		if (safeSetWidget(lines, { placement: "belowEditor" })) runningFrame += 1;
	};
	return {
		start() {
			render();
			if (stopped) return;
			interval = setInterval(render, PROGRESS_FRAME_INTERVAL_MS);
			interval.unref?.();
		},
		taskStarted(task) {
			running.set(task.name, { startedAt: Date.now(), task });
			render();
		},
		taskFinished(result) {
			results.set(result.name ?? result.agent, result);
			running.delete(result.name ?? result.agent);
			render();
		},
		clear() {
			const shouldClearWidget = !stopped;
			stop();
			if (!shouldClearWidget) return;
			try {
				setWidget.call(ui, "pi-subflow-progress", undefined);
			} catch {
				// Ignore stale UI contexts during session replacement/reload.
			}
		},
	};
}

async function runSelectedFlow(mode: FlowMode, params: SubflowToolParams, options: ExecutionOptions): Promise<FlowResult> {
	if (mode === "single") return runSingle({ agent: params.agent ?? "", task: params.task ?? "", cwd: (params as SubagentTask).cwd, role: (params as SubagentTask).role, tools: (params as SubagentTask).tools, model: (params as SubagentTask).model, thinking: (params as SubagentTask).thinking }, options);
	if (mode === "chain") return runChain({ chain: params.chain ?? [] }, options);
	if (mode === "dag") return runDag({ tasks: params.tasks ?? [] }, options);
	return runParallel({ tasks: params.tasks ?? [] }, options);
}

function resolveHistoryPath(path: PiSubflowExtensionOptions["historyPath"], ctx: ExtensionContext): string {
	if (typeof path === "function") return path(ctx);
	return path ?? join(ctx.cwd, ".pi", "subflow", "runs.jsonl");
}

function truncate(value: string, width: number): string {
	return truncateToWidth(value, width, "…");
}

function formatCall(_params: SubflowToolParams): string {
	return "";
}

function formatResult(result: FlowResult, mode: FlowMode): string {
	const completed = result.results.filter((item) => item.status === "completed").length;
	const failed = result.results.filter((item) => item.status === "failed").length;
	const skipped = result.results.filter((item) => item.status === "skipped").length;
	const lines = [
		`subflow · ${mode} · ${result.status}`,
		`${result.results.length} task${result.results.length === 1 ? "" : "s"} · ${completed} completed · ${failed} failed · ${skipped} skipped`,
		...formatResultBody(result, mode),
	];
	if (result.output) lines.push(`final: ${firstLine(result.output)}`);
	return lines.join("\n");
}

function formatResultBody(result: FlowResult, mode: FlowMode): string[] {
	if (mode === "dag") return formatDagResult(result.results);
	return result.results.map((item) => formatTaskResult(item));
}

function formatTaskResult(result: SubagentResult): string {
	const name = result.name ?? result.agent;
	const identity = formatTaskIdentity(result);
	if (result.status === "failed") return `✗ ${name} ${identity}: ${result.error ?? "failed"}`;
	if (result.status === "skipped") return `- ${name} ${identity}: skipped`;
	const summary = result.output ? firstLine(result.output) : "completed";
	return `✓ ${name} ${identity} → ${summary}`;
}

function formatDagResult(results: SubagentResult[]): string[] {
	const roots = results.filter((result) => (result.dependsOn ?? []).length === 0);
	const lines = ["DAG graph"];
	for (const root of roots.length ? roots : results) {
		const rootName = root.name ?? root.agent;
		lines.push(`${rootName} ${formatDagNodeMeta(root)} ${statusIcon(root.status)}`);
		for (const child of results.filter((candidate) => (candidate.dependsOn ?? []).includes(rootName))) {
			lines.push(`  └─ ${child.name ?? child.agent} ${formatDagNodeMeta(child)} ${statusIcon(child.status)}`);
		}
	}
	if (lines.length === 1) lines.push(...results.map((result) => `${result.name ?? result.agent} ${formatDagNodeMeta(result)} ${statusIcon(result.status)}`));
	return lines;
}

function formatTaskIdentity(result: Pick<SubagentResult, "agent" | "model"> | { agent?: string; model?: string }): string {
	return `[${[result.agent ?? "workflow", result.model ?? "default"].join(" · ")}]`;
}

function formatDagNodeMeta(result: SubagentResult): string {
	return `[${[result.agent, result.role ?? "worker", result.model ?? "default"].join(" · ")}]`;
}

const PROGRESS_FRAME_INTERVAL_MS = 60;
const RUNNING_STATUS_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"].map((frame) => `\x1b[32m${frame}\x1b[0m`);

function statusIcon(status: SubagentResult["status"], frame = 0): string {
	if (status === "completed") return "✓";
	if (status === "failed") return "✗";
	if (status === "running") return RUNNING_STATUS_FRAMES[frame % RUNNING_STATUS_FRAMES.length] ?? RUNNING_STATUS_FRAMES[0];
	return "-";
}

function firstLine(value: string): string {
	const line = value.trim().split(/\r?\n/).find((item) => item.trim())?.trim() ?? "";
	return truncate(line, 120);
}

function formatDuration(ms: number): string {
	return `${Math.max(0, Math.round(ms / 1000))}s`;
}
